/**
 * aiRoadmapEngine.js
 * ------------------------------------------------
 * Generates a personalized learning roadmap based on SWOT analysis.
 * Uses Gemini API for generation.
 */

export async function generatePersonalizedRoadmap(swotData) {
    if (!swotData || !swotData.swot) {
        throw new Error("Invalid SWOT data provided for roadmap generation.");
    }

    const { swot } = swotData;

    const prompt = `
You are an expert academic counselor.
Based on the following SWOT analysis of a student, generate a personalized 5-step learning roadmap.
The goal is to leverage strengths, improve weaknesses, seize opportunities, and mitigate threats.

SWOT Analysis:
Strengths: ${swot.strengths.join("; ")}
Weaknesses: ${swot.weaknesses.join("; ")}
Opportunities: ${swot.opportunities.join("; ")}
Threats: ${swot.threats.join("; ")}

Return a JSON object with a single key "roadmap" containing an array of 5 steps.
Each step object must have:
- "step": Number (1-5)
- "title": String (Short, action-oriented title)
- "description": String (Brief explanation of what to do)
- "duration": String (e.g., "1 week", "2 days")
- "status": String (Always "pending")
- "reason": String (A very brief, data-backed explanation of WHY this task is suggested based on their SWOT)

Do not include markdown formatting like \`\`\`json. Just return the raw JSON object.
`;

    try {
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyDXb5osDBC8JEvEhdjsG7ZPiX936HEHHVY`,
            {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: {
                        responseMimeType: "application/json",
                    }
                }),
            }
        );

        const data = await response.json();
        const text = data?.candidates?.[0]?.content?.parts?.[0]?.text;

        if (text) {
            return JSON.parse(text);
        }

        throw new Error("No roadmap generated by AI.");

    } catch (error) {
        console.error("Error generating roadmap:", error);
        // Fallback roadmap if AI fails
        return {
            roadmap: [
                { step: 1, title: "Review Fundamentals", description: "Go back to basics to ensure a strong foundation.", duration: "1 week", status: "pending", reason: "Strong fundamentals are the best base for improving your current subject mastery." },
                { step: 2, title: "Consistent Practice", description: "Dedicate 30 mins daily to study sessions.", duration: "Ongoing", status: "pending", reason: "Daily habit formation is proven to reduce the 'decay' in learning engagement." },
                { step: 3, title: "Engage with Peers", description: "Join 2 group discussions this week.", duration: "1 week", status: "pending", reason: "Peer learning helps clarify complex concepts through multiple perspectives." },
                { step: 4, title: "Take Initiative", description: "Ask one question in every class.", duration: "Ongoing", status: "pending", reason: "Active participation shifts your learning state from passive to proactive." },
                { step: 5, title: "Assess Progress", description: "Review your progress and adjust goals.", duration: "1 day", status: "pending", reason: "Self-reflection ensures your learning path remains aligned with your personal goals." }
            ]
        };
    }
}
